spring.application.name=astro-tracker

spring.mongodb.uri=mongodb+srv://srkrshnvrdhn:kittu123@astrotracker.gjddgqu.mongodb.net/astro_tracker?retryWrites=true&w=majority
nasa.api.key=GcL3gHG6ig05LbUK9rj4yp14c5FjzNgAG64L3IK5
solar.api.key=17b57cb2-e061-4378-a78f-3fa520061d98